inherit_from: .rubocop_todo.yml

# RuboCop configuration for PlebisHub
# Generated: 2025-12-04

plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.2
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'public/**/*'

# Metrics - These are often violated in legacy code, adjust gradually
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/migrate/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/routes.rb'
    - 'config/environments/**/*'
    - 'app/admin/**/*'

# Style - Preferences
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/ClassAndModuleChildren:
  Enabled: false

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

# Rails specific
Rails/I18nLocaleTexts:
  Enabled: false

Rails/Output:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'

# Lint
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

# Naming
Naming/VariableNumber:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

# RSpec specific (when rubocop-rspec is installed)
# RSpec/ExampleLength:
#   Max: 10
#   Exclude:
#     - 'spec/requests/**/*'
#     - 'spec/system/**/*'

# RSpec/MultipleExpectations:
#   Max: 5
#   Exclude:
#     - 'spec/requests/**/*'
#     - 'spec/system/**/*'

# Enable all new cops by default
Gemspec/AddRuntimeDependency:
  Enabled: true

Gemspec/AttributeAssignment:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: false

Layout/EmptyLinesAfterModuleInclusion:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true

Layout/LineContinuationSpacing:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/ArrayLiteralInRegexp:
  Enabled: true

Lint/ConstantOverwrittenInRescue:
  Enabled: true

Lint/ConstantReassignment:
  Enabled: true

Lint/CopDirectiveSyntax:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateMagicComment:
  Enabled: true

Lint/DuplicateMatchPattern:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/DuplicateSetElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Lint/EmptyClass:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/HashNewWithKeywordArgumentsAsDefault:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/ItWithoutArgumentsInBlock:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/LiteralAssignmentInCondition:
  Enabled: true

Lint/MixedCaseRange:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NonAtomicFileOperation:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/NumericOperationWithConstantResult:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RedundantRegexpQuantifiers:
  Enabled: true

Lint/RedundantTypeConversion:
  Enabled: true

Lint/RefinementImportMethods:
  Enabled: true

Lint/RequireRangeParentheses:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/SharedMutableDefault:
  Enabled: true

Lint/SuppressedExceptionInNumberConversion:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UselessRescue:
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

Security/CompoundHash:
  Enabled: true

Security/IoMethods:
  Enabled: true

Style/AccessModifierDeclarations:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayIntersect:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/ComparableClamp:
  Enabled: true

Style/ConcatArrayLiterals:
  Enabled: true

Style/DataInheritance:
  Enabled: true

Style/DirEmpty:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EmptyHeredoc:
  Enabled: true

Style/EndlessMethod:
  Enabled: false

Style/EnvHome:
  Enabled: true

Style/ExactRegexpMatch:
  Enabled: true

Style/FetchEnvVar:
  Enabled: false

Style/FileEmpty:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/MagicCommentFormat:
  Enabled: true

Style/MapCompactWithConditionalBlock:
  Enabled: true

Style/MapIntoArray:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/MapToSet:
  Enabled: true

Style/MinMaxComparison:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NestedFileDirname:
  Enabled: true

Style/NumberedParameters:
  Enabled: false

Style/NumberedParametersLimit:
  Enabled: true

Style/ObjectThen:
  Enabled: true

Style/OpenStructUse:
  Enabled: false

Style/OperatorMethodCall:
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantArrayConstructor:
  Enabled: true

Style/RedundantConstantBase:
  Enabled: true

Style/RedundantCurrentDirectoryInPath:
  Enabled: true

Style/RedundantDoubleSplatHashBraces:
  Enabled: true

Style/RedundantEach:
  Enabled: true

Style/RedundantFilterChain:
  Enabled: true

Style/RedundantHeredocDelimiterQuotes:
  Enabled: true

Style/RedundantInitialize:
  Enabled: true

Style/RedundantLineContinuation:
  Enabled: true

Style/RedundantRegexpArgument:
  Enabled: true

Style/RedundantRegexpConstructor:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/RedundantStringEscape:
  Enabled: true

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Style/SingleLineDoEndBlock:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/SuperArguments:
  Enabled: true

Style/SuperWithArgsParentheses:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/YAMLFileRead:
  Enabled: true
