# frozen_string_literal: true

FactoryBot.define do
  factory :category, class: 'Category' do
    sequence(:name) { |n| "Category #{n}" }
    # slug will be auto-generated by FriendlyId

    # Traits for different category states
    trait :with_posts do
      after(:create) do |category|
        create_list(:post, 3, categories: [category])
      end
    end

    trait :with_one_post do
      after(:create) do |category|
        create(:post, categories: [category])
      end
    end

    trait :with_many_posts do
      after(:create) do |category|
        create_list(:post, 10, categories: [category])
      end
    end

    trait :active do
      with_one_post
    end

    trait :inactive do
      # Category without posts
    end

    trait :with_custom_slug do
      slug { "custom-slug-#{rand(1000)}" }
    end

    # Common category names
    trait :politics do
      name { 'Politics' }
    end

    trait :economy do
      name { 'Economy' }
    end

    trait :culture do
      name { 'Culture' }
    end

    trait :technology do
      name { 'Technology' }
    end
  end
end
